/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liangbin_jni_beautify_JniBeautify */

#ifndef _Included_com_liangbin_jni_beautify_JniBeautify
#define _Included_com_liangbin_jni_beautify_JniBeautify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liangbin_jni_beautify_JniBeautify
 * Method:    getBitmap
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_liangbin_jni_1beautify_JniBeautify_getBitmap
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
